# 2024/07/18(木)
## 🧩 タスクばらし
### プラクティス『Ruby初級』の修了
- [x] 各参考ページを確認
- [x] 書籍『スラスラ読めるRubyふりがなプログラミング』
- [ ] 動画講座
- [ ] 課題取り組み


## 📋 段取り
<details><summary>各参考ページを確認</summary>

- [x] [ホワイの(感動的)Rubyガイド](http://www.aoky.net/articles/why_poignant_guide_to_ruby/chapter-1.html)
- [x] [TryRuby](https://try.ruby-lang.org/)
- [x] [ゼロからわかるRuby超入門の読み方](https://bootcamp.fjord.jp/pages/289)
- [x] [学習を加速させるインデックス読書術](https://qiita.com/dkatsura/items/3364b293ed1451a66a8a)
- [x] [Ruby の公式リファレンスが読めるようになる本](https://zenn.dev/jnchito/books/how-to-read-ruby-reference)
- [x] [オブジェクト指向スクリプト言語 Ruby リファレンスマニュアル](https://docs.ruby-lang.org/ja/latest/doc/index.html)
- [x] [【新人プログラマ応援】公式ドキュメントも読もう - Qiita](https://qiita.com/chooyan_eng/items/cd0d3174b77ff1e02c3f)
</details>

<details><summary>書籍『スラスラ読めるRubyふりがなプログラミング』</summary>

- [x] Chapter 1
- [x] Chapter 2
- [x] Chapter 3
- [x] Chapter 4
</details>

<details><summary>動画講座</summary>

- [ ] [ゼロからわかるRuby超入門動画講座](https://bootcamp.fjord.jp/pages/374)
   - [x] CHAPTER 2
   - [x] CHAPTER 3
   - [x] CHAPTER 4
   - [x] CHAPTER 5
   - [x] CHAPTER 6
   - [x] CHAPTER 7
   - [x] CHAPTER 8
   - [x] CHAPTER 9
   - [x] CHAPTER 10
   - [ ] CHAPTER 11
</details>

<details><summary>課題取り組み</summary>

- [x] ゼロからわかる Ruby 超入門の各章の練習問題
   - [x] CHAPTER 2
   - [x] CHAPTER 3
   - [x] CHAPTER 4
   - [x] CHAPTER 5
   - [x] CHAPTER 6
   - [x] CHAPTER 7
   - [x] CHAPTER 8
   - [x] CHAPTER 9
   - [x] CHAPTER 10
- [ ] [TryRuby](https://try.ruby-lang.org/)
</details>


## ✍🏻 本日の取り組み
### ゼロからわかるRuby超入門動画講座
- CHAPTER 11
   - 11-1 例外処理


## 💡 本日の学び・気付き
### CHAPTER 11

#### 11-1 例外処理
- エラーが起きたときなど、例外的な処理を書くときに**例外処理**という仕組みを使う。

##### 例外とは
- 例外は想定外の問題が起きたときに発生する。
   - 想定外の問題なので、Ruby はエラーメッセージを表示してプログラムを停止させる。
   - **無理に処理を続けるよりは、その場でプログラムを止めた方が安全**という考え方からなるもの。

##### 例外処理の書式
```ruby
begin
   # 例外が発生する可能性がある処理
rescue 例外クラス
   # 例外が発生したときに実行する処理（rescue節）
end
```
- 例外を処理するためには`begin ~ rescue`を使用する。
   - rescue を使って例外処理を書くことで、例外が発生してもプログラムを続行できるようになる。
   - rescue：救助する
```ruby
puts "金額を入力してください"
bill = gets.to_i
puts "割り勘する人数を入力してください"
number = gets.to_i

begin # 例外処理開始。
  warikan = bill / number
  puts "1人あたり#{warikan}円です"
rescue ZeroDivisionError # もし例外クラスZeroDivisionErrorが発生したら以下の処理で助けよ。
  # ZeroDivisionError例外が発生したらメッセージを表示する。
  puts "おっと、0人では割り勘できません" # 文字列「おっと、0人では割り勘できません」を表示せよ。
end # 例外処理終了。

# rescue は「もし、例外クラス〇〇が発生したら以下の処理で助けよ」と読み下そう。
```
- メソッド内で例外処理を書く場合は、begin と end を処理できる。メソッドの初めから rescue までの処理で発生した例外を、rescue節で受け取れる。
```ruby
def warikan(bill, number)
  warikan = bill / number
  puts "1人あたり#{warikan}円です"
rescue ZeroDivisionError
  # ZerDivisionError例外が発生したらメッセージを表示する。
  puts "おっと、0人では割り勘できません"
end

warikan(100, 0)
warikan(100, 1)
warikan(100, 2)

# メソッド内で例外処理を書く場合は、beginとendを省略できる。
# メソッドの初めからrescueまでの処理で発生した例外を、rescue節で受け取れる。
# 7行目のendはdefとセットになっているend。
```
- Ruby 2.5 以降ではブロック内でも begin と end を省略できる。
```ruby
bill = 100 # 数値100を変数billに紐付けせよ。
numbers = [0, 1, 2] # 配列[0, 1, 2]を変数numbersに紐付けせよ。

numbers.each do |number| # 変数numbers内の要素を1つずつ変数numberに紐付け、以下の処理を繰り返せよ。
  warikan = bill / number # 変数billを変数numberで割った結果を変数warikanに紐付けせよ。
  puts "1人あたり#{warikan}円です" # 文字列「1人あたりwarikan円です」を表示せよ。
rescue ZeroDivisionError # 例外クラスZeroDivisionErrorが発生したら以下の処理で助けよ。
  puts "おっと、0人では割り勘できません" # 文字列「おっと、0人では割り勘できません」を表示せよ。
end # ブロック終了。

# do〜endに囲まれた範囲をブロックと呼び、その間に繰り返したい処理を書く。
# 配列の中の要素が順番にブロック変数に紐付けられ、その数だけブロック内の処理が繰り返される。
# ここでのブロック変数は |number| の中の number を指す。
# eachは「1つずつ」、doは「以下の処理」、endは「ブロック終了」と読み下そう。
```

##### 例外をどういうときに使うのか？
- そもそも**例外は使わない方がプログラムとして読みやすいことが多い**。
- 例外は文字通り**例外的な問題に対応するため**に使われる。
- 想定できる問題には、**if文**で分岐するプログラムを書く方が読みやすい。
- **実践的なプログラムでは、ファイルを開けなかったときやネットワークに繋がらなかったときなど、事前に例外が発生するかどうかをチェックできないときに例外処理を使用する**。
- 例外処理は使いすぎると分かりづらくなるため、どういったときに使われるのかを意識すること。

##### 例外オブジェクトの代入
```ruby
begin
   # 例外は発生する可能性がある処理
rescue 例外クラス => e   # 変数eに例外オブジェクトが代入される
   # 例外が発生したときに実行する処理（rescue節）
end
```
- 例外が発生したときに、「何故、例外が発生したのか？」という情報を得たいことがほとんど。そのため、例外オブジェクトを取得して例外の詳細を取得する。
```ruby
def cat(filename)
  # ファイルの内容を表示する。
  File.open(filename) do |file| # ①ファイルを開く。
    file.each_line {|line| puts line } #②ファイルの内容を表示する。
  end # ③ファイルを閉じる。
rescue SystemCallError => e # ④例外処理:例外オブジェクトを変数eに代入。
  puts "--- 例外が発生しました ---"
  puts "例外クラス: #{e.class}" # ⑤
  puts "例外メッセージ: #{e.message}" # ⑥
end

filename = ARGV.first # ⑦コマンドプロンプトの引数を読み込み
cat(filename)

# ①でファイルを開く。ファイル操作には、組み込みライブラリのFileクラスを使う。File.openは引数filenameで指定したファイルを開き、ファイル操作のためのFileオブジェクトを作ってfile変数に代入する。
# ②でファイルの内容を表示。each_lineは配列のeachに似たメソッドで、ファイルの先頭から1行ずつ読み込み、繰り返しline変数に代入する。読み込んだ各行は、putsメソッドで画面に表示する。
# ③でファイル操作のブロックが終わると、開いたファイルが閉じられる。
# ④からが例外処理。受け取る例外クラスとしてSystemCallErrorを指定している。SystemCallErrorはファイル操作などに失敗した時に発生する例外クラス。例外クラスの後ろに=> eという記述が加わる。このeは変数。受け取った例外オブジェクトが変数eに代入される。
# ⑤のe.classで例外オブジェクトのクラス目を表示し、
# ⑥のe.messageで例外のメッセージを表示。classとmessageは、例外クラスで使えるメソッド。
# ⑦でコマンドプロンプトで指定したファイル名を読み込む。ARGVはRubyが用意した特別な定数で、コマンドプロンプトで指定した引数を要素として持つ配列。ARGV.firstで先頭の要素を取得する。
```

##### 例外を表すクラス
- Ruby の例外クラスは階層構造になっている。
- 全ての例外は Exceptionクラスを継承している。
- StandardErrorクラスは通常のプログラムでよく発生する例外を束ねるクラス。
- 変数名やメソッド名を間違えたときに発生する **NameError** や **NoMethodError** だけでなく、**SystemCallError** や **ZeroDivisionError** も StandardErrorクラスのサブクラス。

##### 例外を発生させる - raiseメソッド
- 自分で例外を発生させることができる。
- 例外を発生させるときには`raise`メソッドを使用する。

##### 例外を発生させる書式
```ruby
raise "例外メッセージ"
```

##### ScriptError 例外を発生させる
```ruby
raise ScriptError, "致命的なエラーが発生しました"
```

##### 例外の有無に関わらず必ず処理を実行する - ensure
- 例外の発生有無に関わらず必ず実行する`ensure`という機能がある。

##### ensureの書式
```ruby
begin
   # 例外が発生する可能性のある処理
rescue => e
   # 例外が発生したときに実行する処理
ensure
   # 例外の発生有無に関わらず実行される処理
end
```


## 📍 次回
### ゼロからわかるRuby超入門動画講座
- CHAPTER 11
   - 11-2 クラスの高度な話


## ❤️‍🔥 感想
### 🧑🏻‍💻✍🏻 例外（エラー）は怖くないよ
Ruby の例外処理と呼ばれる仕組みと例外について学びました。読みやすいプログラムを書くためには、**正常な処理**と**例外的な処理を区別して書く**ことが求められると感じました。例外は実行中のプログラムが予期しない状況に遭遇したときに発生するため、エラーとして分類されますが、「**例外（エラー）は怖くないよ**」と自分に言い聞かせて今後も学んでいきます。

## ⏰ 学習時間
- Today:&nbsp;&nbsp;&nbsp; 2 hours 03 min
- Total: 426 hours 02 min
